<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>btnAdmin</name>
   <tag></tag>
   <elementGuidId>52610b8a-e539-46db-8401-ce76109d2544</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//b[.='Admin']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//b[.='Admin']</value>
   </webElementProperties>
</WebElementEntity>
