<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>popupSucces</name>
   <tag></tag>
   <elementGuidId>b8944671-fd27-4d7d-b0fa-9d317bcaee13</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>.message</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>css</name>
      <type>Main</type>
      <value>.message</value>
   </webElementProperties>
</WebElementEntity>
