<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>navPIM</name>
   <tag></tag>
   <elementGuidId>da61391d-1bb9-432f-8d84-276b36d6f9fc</elementGuidId>
   <selectorCollection>
      <entry>
         <key>BASIC</key>
         <value>//b[.='PIM']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>BASIC</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>//b[.='PIM']</value>
   </webElementProperties>
</WebElementEntity>
